name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/dotnet:v1.49.0-noble
      options: --user 0:0
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build & Install
      run: dotnet build
    - name: Ensure browsers are installed
      run: pwsh ./SauceDemoPlaywrightCSharp/bin/Debug/net8.0/playwright.ps1 install --with-deps
    - name: Run tests in chromium
      run: dotnet test --settings ./SauceDemoPlaywrightCSharp/bin/Debug/net8.0/chromium.runsettings 
    - name: Run tests in firefox
      run: dotnet test --settings ./SauceDemoPlaywrightCSharp/bin/Debug/net8.0/firefox.runsettings 
    - name: Run tests in webkit
      run: dotnet test --settings ./SauceDemoPlaywrightCSharp/bin/Debug/net8.0/webkit.runsettings 